# HTTP Cache Server Configuration

[server]
# 服务器监听地址
host = "127.0.0.1"
# 服务器监听端口
port = 8080

[plugins.hls]
# HLS 缓存目录路径
cache_dir = "./cache/hls"
# 分片时长（秒）
segment_duration = 10
# 每个流的最大分片数
max_segments = 30

[plugins.storage]
# 存储根目录路径
root_path = "./storage"
# 最大存储空间（字节）
max_size = 1073741824  # 1GB

[plugins.security]
# 每秒最大请求数
rate_limit = 100
# 允许的来源域名列表
allowed_origins = []

[log]
# 日志级别: debug, info, warn, error
level = "info"
# 是否显示文件名和行号
show_file_line = true
# 是否显示线程ID
show_thread_id = true 